"use client";

import { useState } from "react";
import { generateDescription } from "@/actions/ai";
import { toast } from "sonner";

export function useAIGenerator() {
  const [isGenerating, setIsGenerating] = useState(false);

  async function generate(title: string, category: string, link: string) {
    // 1. Validation Logic
    if (!title) {
      toast.error("Please enter a Title first");
      return null;
    }
    if (!link) {
      toast.error("Please enter a Link first");
      return null;
    }

    setIsGenerating(true);

    // 2. Call Server Action
    const result = await generateDescription(title, category, link);

    setIsGenerating(false);

    // 3. Handle Result
    if (result.error) {
      toast.error(result.error);
      return null;
    }

    if (result.text) {
      toast.success("Description generated by AI!");
      return result.text;
    }

    return null;
  }

  return { isGenerating, generate };
}
